### ISSUE TITLE
curve_fit not working anymore

### ISSUE THREAD

**Issue by abieler** [JuliaOpt/LsqFit.jl#13]
I used the curve_fit function for a while now. After the last Pkg.update() my code crashes though.
I then tried the basic example from the docs which also fails with the following error msg:

```
ERROR: DimensionMismatch("first dimension of A, 20, does not match length of y, 2")
 in gemv! at linalg/matmul.jl:225
 in A_mul_B! at linalg/matmul.jl:91
 in levenberg_marquardt at /home/abieler/.julia/v0.4/Optim/src/levenberg_marquardt.jl:88
 in lmfit at /home/abieler/.julia/v0.4/LsqFit/src/curve_fit.jl:29
 in curve_fit at /home/abieler/.julia/v0.4/LsqFit/src/curve_fit.jl:39
```

Cheers,
Andre

**Comment by abieler** [comment]
After a few git checkouts my guess is it was commit cd297ad6b3f88d215b6556a82e466037ae91d70c which broke it.

**Comment by ChrisRackauckas** [comment]
This got fixed and thus can be closed: https://github.com/JuliaOpt/Optim.jl/issues/182
