### ISSUE TITLE
Levenberg-Marquardt in LsqFit?

### ISSUE THREAD

**Issue by pkofod** [JuliaOpt/LsqFit.jl#15]
I've tried to start a discussion over at https://github.com/JuliaOpt/Optim.jl/issues/207 , but maybe it is just as relevant here.

Since all the `nnls` functionality was recently removed from Optim, I am wondering if Levenberg-Marquardt should be moved as well. It is really a rather special case, that doesn't fit with the rest of the package (in my view). It accepts an `f` an `g`, but they are quite different than our usual `f` and `g!` in Optim.

What do you think? Would it be a bad idea to move the functionality into LsqFit, and obviously still depend on the relevant parts of Optim? Maybe there is even a (need for?) `LeastSquares.jl` algorithm package that I'm not aware of?

**Comment by pkofod** [comment]
@blakejohnson are you maintaining this package? I am getting more and more sure that I don't think levenberg_marquardt should be in Optim. Do you want to host it here instead?

**Comment by blakejohnson** [comment]
@pkofod Yes, I am. I've been holding out hope that we could find an interface in Optim.jl where Levenberg-Marquardt would fit more naturally. But, if `nnls` was also removed, then clearly we are moving away from that direction. Did `nnls` find a new home?

In any case, I'd be okay with moving Levenberg-Marquardt into this package for now.

**Comment by pkofod** [comment]
I don't think nnls found a new home. Tried to search the issues and PRs, but I think it was just killed.
