### ISSUE TITLE
boundserror after Pkg.update() and Pkg.test("LsqFit")

### ISSUE THREAD

**Issue by zahachtah** [JuliaOpt/LsqFit.jl#23]
ERROR: LoadError: LoadError: BoundsError
 in getindex at ./number.jl:21 [inlined]
 in model(::LinSpace{Float64}, ::Float64) at /Users/raukhur/.julia/v0.5/LsqFit/test/curve_fit.jl:2
 in f at /Users/raukhur/.julia/v0.5/LsqFit/src/curve_fit.jl:38 [inlined]
 in #lmfit#1(::Array{Any,1}, ::Function, ::LsqFit.#f#3{#model,LinSpace{Float64},Array{Float64,1}}, ::Array{Float64,1}) at /Users/raukhur/.julia/v0.5/LsqFit/src/curve_fit.jl:31
 in #curve_fit#2(::Array{Any,1}, ::Function, ::#model, ::LinSpace{Float64}, ::Array{Float64,1}, ::Array{Float64,1}) at /Users/raukhur/.julia/v0.5/LsqFit/src/curve_fit.jl:39
 in curve_fit(::Function, ::LinSpace{Float64}, ::Array{Float64,1}, ::Array{Float64,1}) at /Users/raukhur/.julia/v0.5/LsqFit/src/curve_fit.jl:38
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in macro expansion; at /Users/raukhur/.julia/v0.5/LsqFit/test/runtests.jl:13 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/raukhur/.julia/v0.5/LsqFit/test/curve_fit.jl, in expression starting on line 9
while loading /Users/raukhur/.julia/v0.5/LsqFit/test/runtests.jl, in expression starting on line 11

Maybe something with new Optim.jl version?

**Comment by blakejohnson** [comment]
Please provide `versioninfo()` and git SHA of the LsqFit.jl version where you see this error. Thanks!

**Comment by zahachtah** [comment]
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)

could you give me a hint how to find the SHA for the package? trying to look in the folder .jlia/v0.5/LsqFit/ but can't see it

**Comment by zahachtah** [comment]
I have
 - LsqFit                        0.0.2

**Comment by zahachtah** [comment]
update: I did Pkg.checkout("LsqFit) and then build and now the test passes but lots of warnings, e.g. :

WARNING: Problem solving for delta_x: predicted residual increase.
3.3671457655432 (predicted_residual) >
3.3582265007798275 (residual) + 4.440892098500626e-16 (eps)

and

WARNING: MultivariateOptimizationResults(method,initial_x,minimizer,minimum,iterations,iteration_converged,x_converged,x_tol,f_converged,f_tol,g_converged,g_tol,trace,f_calls,g_calls) is deprecated, use MultivariateOptimizationResults(method,initial_x,minimizer,minimum,iterations,iteration_converged,x_converged,x_tol,f_converged,f_tol,g_converged,g_tol,trace,f_calls,g_calls,0) instead.

**Comment by mzaffalon** [comment]
It looks like the `BoundsError` is generated at https://github.com/JuliaOpt/LsqFit.jl/blob/v0.0.2/src/curve_fit.jl#L30 and the correct call should be `result.minimizer`.
@blakejohnson Will you maintainers be tagging a new release soon or would you like a PR?

**Comment by blakejohnson** [comment]
I'll tag a new release.

**Comment by mzaffalon** [comment]
@blakejohnson Thank you.

**Comment by blakejohnson** [comment]
I believe this is now fixed in LsqFit v0.1.0.
