### ISSUE TITLE
Adding a parameter to the curve_fit composite to obtain the r-squared of a linear regression?

### ISSUE THREAD

**Issue by aeroflux** [JuliaOpt/LsqFit.jl#9]
Would be it possible to add a parameter to the curve_fit composite to obtain the r-squared of a linear regression?

Cheers

**Comment by mlubin** [comment]
I would recommend using one of the statistical packages like https://github.com/JuliaStats/GLM.jl for this.

**Comment by aeroflux** [comment]
Thanks for the reply. I really like the simplicity of this package and wanted to avoid rearranging my data into dataFrames for GLM.
